# Generated by Django 4.0.3 on 2023-10-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binvo',
            name='section_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
